config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "jobs#index"

  resource :users

  resources :applications

  resources :jobs, :except => [:index]
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :job
  belongs_to :applicant, :class_name => 'User', :foreign_key => 'user_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :job_title, :description, :employer_name, :location, :employer_id, presence: true
  belongs_to :user, :class_name => 'User', :foreign_key => 'employer_id'
  has_many :applications, :dependent => :destroy
  has_many :applicants, :through => :applications, :class_name => 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
   "applicant" => 0,
   "employer" => 1,
   "admin" => 2
  }

  has_many :jobs, :foreign_key => 'employer_id', :dependent => :destroy
  has_many :applications, :foreign_key => 'user_id'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    if current_user.applicant?
      @applications = current_user.applications
    else
      @applications = Application.all
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)
    if @application.save
      redirect_to root_path, alert: "Your job application has been submitted"
    else
      redirect_to new_application_path, alert: "Error: Your application could not be submitted"
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:user_id, :job_id, :notes)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  before_action :set_job, :only => [:update, :edit, :destroy]

  def new
   # constant checking with employer? method needs to be DRYed up
   if current_user && current_user.employer?
    @job = Job.new
   else
    redirect_to root_path, alert: "Only employers can add a job listing"
   end

  end

  def create
    if current_user && current_user.employer?
      @job = Job.new(job_params)

      if @job.save
        redirect_to @job, alert: "New Job listing created"
      else
        render new_job_path, alert: "New Job listing could not be created"
      end
    else
      redirect_to root_path, alert: "Only employers can add a job opening"
    end
  end

  def edit

  end

  def show
    @job = Job.find(params[:id])
    @applied = has_application?
    render :show
  end

  def update
    if current_user && current_user.employer?
      @job.update(job_params)
      redirect_to @job, alert: "Job listing updated"
    else
      redirect_to root_path, alert: "Only employers can add a job opening"
    end
  end

  def index
    if current_user && current_user.employer?
      @jobs = current_user.jobs
    else
      @jobs = Job.all
    end

    render :index
  end

  def destroy
    if current_user.id == @job.employer_id
      @job.destroy
      redirect_to root_path, alert: "#{@job.title} job opening is deleted"
    else
      redirect_to root_path, alert: "Only employers can delete a job opening"
    end
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:job_title, :description, :employer_name, :location, :employer_id)
  end

  def has_application?
    @app = Application.find_by(job_id: @job)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <%= f.hidden_field :user_id, :value => params[:user_id] %>
  <%= f.hidden_field :job_id, :value => params[:job_id] %>

  <div class="field">
    <%= f.label :notes, "Notes" %>
    <%= f.text_area :notes, label: "Notes"  %>
  </div>

  <br>

  <%= f.submit "Submit Application" %>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Applications</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @applications %>
      <% @applications.each do |application| %>
        <ul>
          <div>Job Title: <%= application.job.job_title %></div>
          <div>Company: <%= application.job.employer_name %></div>
          <div>Submission Date: <%= application.created_at.strftime("%d/%m/%Y") %></div>
          <div>Notes: <%= application.notes %></div>
        </ul>
      <% end %>
    <% else %>
      <h2>No applications yet</h2>
    <% end %>
  </tbody>
</table>

<br>

app/views/applications/new.html.erb
<h1>New Job Application</h1>

<%= render 'form', application: @application %>
<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<h3><%= @application.job.job_title %></h3>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>

  <div class="field">
    <%= f.label :job_title, "Job title" %>
    <%= f.text_field :job_title %>
  </div>

<!-- Need to autopopulate Employer name -->
  <div class="field">
    <%= f.label :employer_name, "Employer Name" %>
    <%= f.text_field :employer_name, value: current_user.company, placeholder: current_user.company  %>
  </div>

  <div class="field">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :location, "Location" %>
    <%= f.text_field :location %>
  </div>

  <%= f.hidden_field :employer_id, :value => current_user.id unless @job.employer_id %>

  <br>

  <%= f.submit %>
  <p class="required">All fields are required</p>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job Listing</h1>
<%= render 'form' %>

app/views/jobs/index.html.erb
<% if @jobs.blank? %>
    <h2>No jobs currently available, check back soon</h2>

<% else %>
  <h2>Current Job Listings:</h2>

	<% @jobs.each do |job| %>
		<div>
	     	<div>Job Title: <%= link_to job.job_title, job_path(job) %></div>
	    	<div>Employer: <%= job.employer_name %></div>
	    	<div>Location: <%= job.location %></div>
	    	<div>Description: <%= job.description %></div>
	    	<div>Posting Date: <%= job.updated_at.strftime("%d/%m/%Y") %></div>
	    </div>

	    <% if current_user && current_user.employer? %>
		    <ul>
		    	<% job.applications.each do |app| %>
		    		<li>Applicant Name: <%= app.applicant.name %></li>
		    		<li>Date Submitted: <%= app.created_at.strftime("%d/%m/%Y")%></li>
		    	<% end %>
		    </ul>
	    <% end %>
	    <br>
	<% end %>
 <% end %>

app/views/jobs/new.html.erb
<h1>New Job Listing</h1>

<%= render 'form' %>
<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<h3><%= @job.job_title %></h3>

<div>
	<div>Employer: <%= @job.employer_name %></div>
	<div>Location: <%= @job.location %></div>
	<div>Description: <%= @job.description %></div>
	<div>Posting Date: <%= @job.updated_at.strftime("%d/%m/%Y") %></div>
</div>
<br>
<% if current_user && current_user.applicant? %>
  <% if @app && @app.id.present? %>
    <div>You have already applied to this Job</div>
    <div>See the <%= link_to "List My Applications", applications_path %> for more info</div>
  <% else %>
  	<%= link_to "Submit Application", new_application_path(job_id: @job.id, user_id: current_user), method: "get", class: "btn" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navigation">
  <% if !current_user %>
    <ul>
      <li><%= link_to "Log in", new_user_session_path %></li>
    </ul>

  <% else %>
    <div class="salutation">
      Hello, <%= current_user.name %>
    </div>

    <% if current_user.employer? %>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Post a new job listing", new_job_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, :method => 'delete' %></li>
      </ul>

    <% else %>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "List My Applications", applications_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, :method => 'delete' %></li>
      </ul>
    <% end %>
  <% end %>
</div>

<!--  currently only employers and applicants in ths app - would update logic if adding other types of users -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job Board</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
      <div class="container">
        <div id="title"><%= link_to "Job Board", root_path %></div>
        <header>
          <%= render "layouts/navigation" %>
        </header>

        <div class="main">
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>

      </div>
    </body>
  </body>
</html>